const images = {
  //   homeInActive: require("../../assets/icons/home_none.png"),
  //   homeActive: require("../../assets/icons/home.png"),
  //   heartInActive: require("../../assets/icons/heart_none.png"),
  //   heartActive: require("../../assets/icons/heart.png"),
  //   profileInActive: require("../../assets/icons/person_none.png"),
  //   profileActive: require("../../assets/icons/person.png"),
  //   add: require("../../assets/icons/add_circle.png"),
  //   login: require("../../assets/imagesfile/login.png"),
  //   register: require("../../assets/imagesfile/register.png"),
  image1: require("../../assets/onboarding/pic1.jpg"),
  image2: require("../../assets/onboarding/pic2.jpg"),
  image3: require("../../assets/onboarding/pic3.jpg"),
  image4: require("../../assets/onboarding/pic4.jpg"),
  image5: require("../../assets/onboarding/pic5.jpg"),
  image6: require("../../assets/onboarding/pic6.jpg"),

  //   empty: require("../../assets/imagesfile/error.png"),
  //   delete: require("../../assets/icons/del.png"),
  //   location: require("../../assets/icons/location_on.png"),
  //   calendar: require("../../assets/icons/calendar.png"),
  //   teacher: require("../../assets/icons/teacher.png"),
  //   love: require("../../assets/icons/love.png"),
  //   cross: require("../../assets/icons/cross.png"),
  //   backArrow: require("../../assets/icons/backWhite.png"),
  //   phone: require("../../assets/icons/phoneBlue.png"),
  //   email: require("../../assets/icons/messageBlue.png"),
};
export default images;
